name: Purge Boilerplate

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  purge-boilerplate:
    runs-on: ubuntu-latest
    if: github.repository != 'kenso312/nestjs-v9-webpack-boilerplate'
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Files and Directories
        run: |
          rm -rf .github \
            CHANGELOG.md \
            LICENSE \
            SECURITY.md

      - name: Commit and Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit --amend -am "init: first commit"
          git push --no-verify -f
