name: Merge Dependabot Pull Request to Dev Branch

on:
  pull_request_target:
    branches:
      - dev

jobs:
  merge-dependabot-pr-to-dev-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Merge Dependabot Pull Request to Dev Branch
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          MERGE_DELETE_BRANCH: true
          MERGE_FILTER_AUTHOR: dependabot[bot]
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
