name: Rebase Dev Branch

on:
  workflow_run:
    workflows:
      - Merge to Main Branch
    types:
      - completed

jobs:
  rebase-dev-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Pushing Back to Dev Branch
        run: |
          git fetch origin main
          git rebase origin/main
          git push origin dev
